#!/usr/bin/env python3
"""Build firmware header views of the frozen Sourdough output vocabulary.

Writes:
  - src/generated/sourdough_words.h (class id -> displayed word string)
  - src/generated/sourdough_out2in.h (class id -> input embedding token id)

Follows the validation and generation structure from slvDev/esp32-ai-barista.
"""

import argparse
import json
from pathlib import Path
from typing import List, Tuple

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VOCAB = PROJECT_ROOT / "data" / "sourdough" / "vocab.json"
DEFAULT_LAYOUT = PROJECT_ROOT / "data" / "sourdough" / "layout.json"
DEFAULT_OUT_DIR = PROJECT_ROOT / "src" / "generated"

SPECIALS = ("<pad>", "<bos>", "<eos>", "<unk>")
WORDS_PER_LINE = 8
IDS_PER_LINE = 16
BANNER = "// Generated by pc_tools/generate_vocab_headers.py - DO NOT EDIT BY HAND"


def is_int(value) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def const_name(token: str) -> str:
    return "SOURDOUGH_" + token.strip("<>").upper()


def c_string(word: str) -> str:
    for ch in word:
        if not 0x20 <= ord(ch) <= 0x7E:
            raise SystemExit(f"word {word!r} contains non-printable ASCII")
    return '"' + word.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load(vocab_path: Path, layout_path: Path) -> Tuple[List[str], List[int], dict]:
    with open(vocab_path, "r", encoding="utf-8") as f:
        vocab = json.load(f)
    with open(layout_path, "r", encoding="utf-8") as f:
        layout = json.load(f)

    words = [entry["token"] for entry in vocab["tokens"]]
    out2in = layout["out2in"]
    bpe_vocab = layout["bpe_vocab"]
    total = layout["total"]
    n_words = layout["n_words"]

    # Basic type and length checks
    if len(words) != n_words or len(out2in) != n_words:
        raise SystemExit(f"Size mismatch: n_words={n_words}, words={len(words)}, out2in={len(out2in)}")
    if tuple(words[: len(SPECIALS)]) != SPECIALS:
        raise SystemExit(f"First 4 tokens must be {SPECIALS}, found {words[:len(SPECIALS)]}")
    if len(set(out2in)) != len(out2in):
        raise SystemExit("Duplicate ID in out2in mapping")
    if min(out2in) < 0 or max(out2in) >= total:
        raise SystemExit("out2in ID out of [0, total) range")

    appended_ids = [tid for tid in out2in if tid >= bpe_vocab]
    if appended_ids != list(range(bpe_vocab, total)):
        raise SystemExit("Appended IDs are not contiguous range(bpe_vocab, total)")

    return words, out2in, layout


def format_words_header(words: List[str]) -> str:
    lines = [
        BANNER,
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define SOURDOUGH_WORD_COUNT {len(words)}",
    ]
    for idx, token in enumerate(SPECIALS):
        lines.append(f"#define {const_name(token)} {idx}")
    lines.extend([
        "",
        "static const char *const SOURDOUGH_WORDS[SOURDOUGH_WORD_COUNT] = {",
    ])
    chunk = []
    for w in words:
        chunk.append(c_string(w))
        if len(chunk) == WORDS_PER_LINE:
            lines.append("  " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("  " + ", ".join(chunk) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def format_out2in_header(out2in: List[int]) -> str:
    lines = [
        BANNER,
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define SOURDOUGH_OUT2IN_COUNT {len(out2in)}",
        "",
        "static const uint16_t SOURDOUGH_OUT2IN[SOURDOUGH_OUT2IN_COUNT] = {",
    ]
    chunk = []
    for tid in out2in:
        chunk.append(f"{tid:5d}")
        if len(chunk) == IDS_PER_LINE:
            lines.append("  " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("  " + ", ".join(chunk) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate sourdough_words.h and sourdough_out2in.h")
    parser.add_argument("--vocab", type=Path, default=DEFAULT_VOCAB, help="Path to vocab.json")
    parser.add_argument("--layout", type=Path, default=DEFAULT_LAYOUT, help="Path to layout.json")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR, help="Directory to emit C headers")
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    words, out2in, layout = load(args.vocab, args.layout)

    words_header_path = args.out_dir / "sourdough_words.h"
    out2in_header_path = args.out_dir / "sourdough_out2in.h"

    words_header_path.write_text(format_words_header(words), encoding="utf-8")
    out2in_header_path.write_text(format_out2in_header(out2in), encoding="utf-8")

    print(f"✓ Wrote {words_header_path} ({len(words)} classes)")
    print(f"✓ Wrote {out2in_header_path} ({len(out2in)} mappings)")


if __name__ == "__main__":
    main()
