#!/usr/bin/env python3
"""Generate C header vocab.h from tokenizer.json for ESP32 on-device decoding."""

import json
import re
from pathlib import Path

import shutil

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_TOK = PROJECT_ROOT / "data" / "sourdough" / "tokenizer.json"
PC_TOK = PROJECT_ROOT / "pc_tools" / "tokenizer.json"
OUT_DIR = PROJECT_ROOT / "src" / "generated"
OUT_PATH = OUT_DIR / "vocab.h"

if DATA_TOK.exists():
    TOK_PATH = DATA_TOK
    shutil.copy2(DATA_TOK, PC_TOK)
else:
    TOK_PATH = PC_TOK

with open(TOK_PATH, "r", encoding="utf-8") as f:
    t = json.load(f)

vocab = t["model"]["vocab"]
inv_vocab = {v: k for k, v in vocab.items()}
n_vocab = max(inv_vocab.keys()) + 1

blob = []
off = [0]

for i in range(n_vocab):
    if i in inv_vocab:
        token = inv_vocab[i]
        # Byte fallback token check
        match = re.match(r"^<0x([0-9A-Fa-f]{2})>$", token)
        if match:
            b = bytes([int(match.group(1), 16)])
            blob.extend(b)
        else:
            # Replace ByteLevel BPE leading space character (Ġ / \u0120) with space
            token = token.replace("\u0120", " ").replace("\u2581", " ")
            b = token.encode("utf-8")
            blob.extend(b)
        off.append(len(blob))
    else:
        off.append(len(blob))

OUT_DIR.mkdir(parents=True, exist_ok=True)

with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by pc_tools/generate_vocab.py\n")
    f.write("#ifndef VOCAB_H\n#define VOCAB_H\n\n")
    f.write(f"#define VOCAB_N {n_vocab}\n\n")
    f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n  ")
    for i, byte in enumerate(blob):
        f.write(f"{byte},")
        if (i + 1) % 20 == 0:
            f.write("\n  ")
    f.write("\n};\n\n")
    f.write(f"static const unsigned int VOCAB_OFF[{n_vocab + 1}] = {{\n  ")
    for i, o in enumerate(off):
        f.write(f"{o},")
        if (i + 1) % 20 == 0:
            f.write("\n  ")
    f.write("\n};\n\n#endif // VOCAB_H\n")

print(f"✓ Generated {OUT_PATH} ({n_vocab} tokens, {len(blob)} bytes)")
