#!/usr/bin/env python3
"""Generate BTK1 tokenizer asset header for ESP32 on-device BPE encoding."""

import hashlib
import json
import struct
from pathlib import Path

import shutil

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_TOK = PROJECT_ROOT / "data" / "sourdough" / "tokenizer.json"
PC_TOK = PROJECT_ROOT / "pc_tools" / "tokenizer.json"
OUT_PATH = PROJECT_ROOT / "src" / "generated" / "tokenizer_asset.h"

if DATA_TOK.exists():
    TOK_PATH = DATA_TOK
    shutil.copy2(DATA_TOK, PC_TOK)
else:
    TOK_PATH = PC_TOK

with open(TOK_PATH, "r", encoding="utf-8") as f:
    tok_data = json.load(f)

vocab = tok_data["model"]["vocab"]
merges = tok_data["model"]["merges"]
active_vocab = len(vocab)
merge_count = len(merges)

# Compute standard ByteLevel byte-to-char mapping
bs = list(range(ord('!'), ord('~') + 1)) + list(range(ord('¡'), ord('¬') + 1)) + list(range(ord('®'), ord('ÿ') + 1))
cs = bs[:]
n = 0
for b in range(256):
    if b not in bs:
        bs.append(b)
        cs.append(256 + n)
        n += 1
byte_to_char = {b: chr(c) for b, c in zip(bs, cs)}

# Byte table: 256 uint16
byte_table = bytearray()
for b in range(256):
    ch = byte_to_char[b]
    tid = vocab.get(ch, 0)
    byte_table.extend(struct.pack("<H", tid))

# Merge entries: key = (left << 16) | right, rank
merge_entries = []
merge_base = None

for rank, m in enumerate(merges):
    pair = m if isinstance(m, list) else m.split()
    left_str, right_str = pair[0], pair[1]
    left_id = vocab[left_str]
    right_id = vocab[right_str]
    joined = left_str + right_str
    target_id = vocab[joined]
    if merge_base is None:
        merge_base = target_id
    key = (left_id << 16) | right_id
    merge_entries.append((key, rank))

# Sort merges by key ascending for binary search
merge_entries.sort(key=lambda x: x[0])

merges_bytes = bytearray()
for key, rank in merge_entries:
    merges_bytes.extend(struct.pack("<IH", key, rank))

# Hash provenance (28 bytes)
tok_bytes = TOK_PATH.read_bytes()
sha28 = hashlib.sha256(tok_bytes).digest()[:28]

# Header (52 bytes)
#   0: magic "BTK1" (4)
#   4: version = 2 (4)
#   8: active_vocab (4)
#  12: merge_count (4)
#  16: reserved = 0 (4)
#  20: merge_base (4)
#  24: sha28 (28)
header = struct.pack("<4sIIIII28s", b"BTK1", 2, active_vocab, merge_count, 0, merge_base, sha28)

asset = bytearray()
asset.extend(header)
asset.extend(byte_table)
asset.extend(merges_bytes)

OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by pc_tools/generate_tokenizer_asset.py\n")
    f.write("#ifndef TOKENIZER_ASSET_H\n#define TOKENIZER_ASSET_H\n\n")
    f.write(f"#define TOKENIZER_ASSET_SIZE {len(asset)}\n\n")
    f.write(f"static const unsigned char TOKENIZER_ASSET[{len(asset)}] = {{\n  ")
    for i, byte in enumerate(asset):
        f.write(f"0x{byte:02x},")
        if (i + 1) % 20 == 0:
            f.write("\n  ")
    f.write("\n};\n\n#endif // TOKENIZER_ASSET_H\n")

print(f"✓ Generated {OUT_PATH} ({len(asset):,} bytes, vocab={active_vocab}, merges={merge_count})")
