#!/usr/bin/env python3
"""Generate sub-vocabulary prediction (hierarchical token clustering) headers for sourdough model.

Clusters the output head weights into K sub-vocabulary clusters.
Generates:
  - src/generated/sourdough_subvocab.h

At inference time, dot products are first evaluated against the K cluster centroids.
Only tokens in the top-M predicted clusters (plus guaranteed special tokens) are evaluated,
reducing the output head computation by >85% while preserving generation fidelity.
"""

import argparse
from pathlib import Path
import struct
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BIN = PROJECT_ROOT / "pc_tools" / "sourdough_q4.bin"
DEFAULT_OUT = PROJECT_ROOT / "src" / "generated" / "sourdough_subvocab.h"
GOLDEN_NPZ = PROJECT_ROOT / "pc_tools" / "golden.npz"

NUM_CLUSTERS = 16
DEFAULT_TOP_CLUSTERS = 4
ALWAYS_INCLUDE = [0, 1, 2, 3, 4, 5, 6, 7, 8]  # Specials + punctuation (. , ! ?)


def load_head_weights(bin_path: Path):
    with open(bin_path, "rb") as f:
        data = f.read()

    hdr = data[:56]
    magic, ver, hdr_bytes, flags = struct.unpack("<IIII", hdr[:16])
    vocab, out_vocab = struct.unpack("<II", hdr[16:24])
    dim, n_layers, n_heads, ffn, ple_dim, seq_len, group = struct.unpack(
        "<iiiiiii", hdr[24:52]
    )

    row_bytes = (dim + 1) // 2
    n_groups = (dim + group - 1) // group
    total_out_head_bytes = 4 + out_vocab * row_bytes + out_vocab * n_groups * 2

    head_start = len(data) - total_out_head_bytes
    p = head_start + 4
    codes = np.frombuffer(data[p : p + out_vocab * row_bytes], dtype=np.uint8).reshape(
        out_vocab, row_bytes
    )
    p += out_vocab * row_bytes
    scales_fp16 = np.frombuffer(
        data[p : p + out_vocab * n_groups * 2], dtype=np.float16
    ).reshape(out_vocab, n_groups)

    w8 = np.zeros((out_vocab, dim), dtype=np.int8)
    for j in range(dim):
        byte = codes[:, j >> 1]
        code = (byte >> 4) if (j & 1) else (byte & 0xF)
        w8[:, j] = code.astype(np.int8) - 8

    w_float = np.zeros((out_vocab, dim), dtype=np.float32)
    for gi in range(n_groups):
        b = gi * group
        e = min(b + group, dim)
        w_float[:, b:e] = w8[:, b:e].astype(np.float32) * scales_fp16[
            :, gi : gi + 1
        ].astype(np.float32)

    return w_float, w8, dim, out_vocab


def cluster_head(w_float: np.ndarray, k: int = NUM_CLUSTERS, seed: int = 13):
    norms = np.maximum(np.linalg.norm(w_float, axis=1, keepdims=True), 1e-8)
    norm_w = w_float / norms

    np.random.seed(seed)
    centroids = norm_w[np.random.choice(len(norm_w), k, replace=False)].copy()
    for _ in range(40):
        sims = norm_w @ centroids.T
        labels = np.argmax(sims, axis=1)
        for i in range(k):
            mask = labels == i
            if np.any(mask):
                c = np.mean(norm_w[mask], axis=0)
                centroids[i] = c / max(np.linalg.norm(c), 1e-8)

    return centroids, labels


def quantize_centroids(centroids: np.ndarray):
    k, dim = centroids.shape
    c_i8 = np.zeros((k, dim), dtype=np.int8)
    scales = np.zeros(k, dtype=np.float32)

    for i in range(k):
        c = centroids[i]
        c_max = float(np.max(np.abs(c)))
        if c_max < 1e-8:
            c_max = 1e-8
        scale = c_max / 127.0
        q = np.clip(np.round(c / scale), -127, 127).astype(np.int8)
        c_i8[i] = q
        scales[i] = scale

    return c_i8, scales


def generate_header(
    out_path: Path,
    c_i8: np.ndarray,
    scales: np.ndarray,
    labels: np.ndarray,
    out_vocab: int,
    dim: int,
):
    k = len(scales)
    cluster_tokens = [[] for _ in range(k)]
    for tok, cl in enumerate(labels):
        cluster_tokens[cl].append(tok)

    counts = [len(toks) for toks in cluster_tokens]
    offsets = []
    curr = 0
    flat_tokens = []
    for toks in cluster_tokens:
        offsets.append(curr)
        flat_tokens.extend(toks)
        curr += len(toks)

    lines = []
    lines.append(
        "// Generated by pc_tools/generate_subvocab.py - DO NOT EDIT BY HAND"
    )
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append("")
    lines.append(f"#define SOURDOUGH_SUBVOCAB_NUM_CLUSTERS {k}")
    lines.append(f"#define SOURDOUGH_SUBVOCAB_DIM {dim}")
    lines.append(f"#define SOURDOUGH_SUBVOCAB_OUT_VOCAB {out_vocab}")
    lines.append(
        f"#define SOURDOUGH_SUBVOCAB_DEFAULT_TOP_CLUSTERS {DEFAULT_TOP_CLUSTERS}"
    )
    lines.append(
        f"#define SOURDOUGH_SUBVOCAB_ALWAYS_COUNT {len(ALWAYS_INCLUDE)}"
    )
    lines.append("")

    # Guaranteed tokens
    lines.append(
        f"static const uint16_t SOURDOUGH_SUBVOCAB_ALWAYS_INCLUDE[{len(ALWAYS_INCLUDE)}] = {{"
    )
    lines.append("    " + ", ".join(str(t) for t in ALWAYS_INCLUDE))
    lines.append("};")
    lines.append("")

    # Centroid scales
    lines.append(
        f"static const float SOURDOUGH_SUBVOCAB_SCALES[{k}] = {{"
    )
    scale_strs = [f"{s:.8e}f" for s in scales]
    for i in range(0, k, 4):
        lines.append("    " + ", ".join(scale_strs[i : i + 4]) + ",")
    lines.append("};")
    lines.append("")

    # Offsets and counts
    lines.append(
        f"static const uint16_t SOURDOUGH_SUBVOCAB_OFFSETS[{k}] = {{"
    )
    for i in range(0, k, 8):
        lines.append("    " + ", ".join(f"{offsets[j]:4d}" for j in range(i, min(i + 8, k))) + ",")
    lines.append("};")
    lines.append("")

    lines.append(
        f"static const uint16_t SOURDOUGH_SUBVOCAB_COUNTS[{k}] = {{"
    )
    for i in range(0, k, 8):
        lines.append("    " + ", ".join(f"{counts[j]:4d}" for j in range(i, min(i + 8, k))) + ",")
    lines.append("};")
    lines.append("")

    # Flat token indices
    lines.append(
        f"static const uint16_t SOURDOUGH_SUBVOCAB_TOKENS[{out_vocab}] = {{"
    )
    for i in range(0, out_vocab, 16):
        chunk = flat_tokens[i : i + 16]
        lines.append("    " + ", ".join(f"{t:4d}" for t in chunk) + ",")
    lines.append("};")
    lines.append("")

    # Centroids table (aligned 16 for SIMD)
    lines.append(
        f"alignas(16) static const int8_t SOURDOUGH_SUBVOCAB_CENTROIDS[{k}][{dim}] = {{"
    )
    for i in range(k):
        lines.append("    {")
        for j in range(0, dim, 16):
            chunk = c_i8[i, j : j + 16]
            lines.append("        " + ", ".join(f"{int(v):4d}" for v in chunk) + ",")
        lines.append("    },")
    lines.append("};")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"✓ Wrote {out_path} ({out_path.stat().st_size:,} bytes)")


def verify_against_golden(c_i8: np.ndarray, scales: np.ndarray, labels: np.ndarray, w_float: np.ndarray):
    if not GOLDEN_NPZ.exists():
        return
    golden = np.load(GOLDEN_NPZ)
    golden_logits = golden["logits"]
    x, _, _, _ = np.linalg.lstsq(w_float, golden_logits, rcond=None)

    # Compute cluster scores with quantized centroids
    c_float = c_i8.astype(np.float32) * scales[:, None]
    c_scores = c_float @ x

    top_m = np.argsort(c_scores)[-DEFAULT_TOP_CLUSTERS:]
    active = np.where(np.isin(labels, top_m))[0]
    active = np.unique(np.concatenate([active, ALWAYS_INCLUDE]))

    best_golden = int(np.argmax(golden_logits))
    top5_golden = [int(t) for t in np.argsort(golden_logits)[-5:]]

    print(f"\n--- Sub-Vocabulary Verification ---")
    print(f"Clusters: {NUM_CLUSTERS}, Top-M selected: {DEFAULT_TOP_CLUSTERS}")
    print(f"Candidate tokens evaluated: {len(active)} / {len(golden_logits)} ({len(active)/len(golden_logits)*100:.1f}%)")
    print(f"Reduction in dot products: {(1.0 - (len(active) + NUM_CLUSTERS)/len(golden_logits))*100:.1f}%")
    print(f"Golden Argmax token ({best_golden}) in candidates: {best_golden in active}")
    top5_hits = sum(t in active for t in top5_golden)
    print(f"Top-5 Golden tokens in candidates: {top5_hits} / 5")
    assert best_golden in active, "Error: Top-1 golden token must be in predicted candidate pool!"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bin", type=Path, default=DEFAULT_BIN, help="Path to sourdough_q4.bin")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Path to output sourdough_subvocab.h")
    parser.add_argument("--clusters", type=int, default=NUM_CLUSTERS, help="Number of clusters")
    parser.add_argument("--seed", type=int, default=13, help="Random seed for k-means")
    args = parser.parse_args()

    print(f"Loading output head from {args.bin}...")
    w_float, w8, dim, out_vocab = load_head_weights(args.bin)
    print(f"Loaded head: {out_vocab} tokens x {dim} dimensions")

    print(f"Clustering into {args.clusters} clusters (seed={args.seed})...")
    centroids, labels = cluster_head(w_float, k=args.clusters, seed=args.seed)

    print("Quantizing centroids to int8 with float scales...")
    c_i8, scales = quantize_centroids(centroids)

    print(f"Generating C header {args.out}...")
    generate_header(args.out, c_i8, scales, labels, out_vocab, dim)

    verify_against_golden(c_i8, scales, labels, w_float)


if __name__ == "__main__":
    main()
