[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions.csv
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi   ; N16R8: QIO flash + Octal PSRAM
build_flags =
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -O3
  -I src
board_upload.flash_size = 16MB
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^7.3

[env:native]
platform = native
build_src_filter = -<main.cpp> -<simd_dotp.S>
